package com.itunes.integration.favorites.dao;

import com.itunes.integration.favorites.entities.FavoriteArtist;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

/**
 * Repository for handling Favorite Artist list.
 */
@Repository
public interface FavoriteArtistRepository extends CrudRepository<FavoriteArtist, Long> {

    /**
     * Find entry by userId. Body auto-generated by JPA
     * @param userId Criteria to find with
     * @return found object, or null if nothing is found
     */
    FavoriteArtist findByUserId(final String userId);
}
